AllCops:
  Exclude:
    - 'spec/fixtures/**/*'
    - 'db/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - lib/tasks/auto_annotate_models.rake

  TargetRubyVersion: 2.5.3

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/Documentation:
  Exclude:
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - app/helpers/application_helper.rb
    - app/controllers/application_controller.rb
    - db/migrate/*
    - spec/**/*
    - app/decorators/*

Rails/CreateTableWithTimestamps:
  Enabled: false
