version: "3"

services:
  app:
    container_name: currency_rate-app
    image: registry.rezerbit.com/currency_rate/app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    working_dir: /app
    command: /bin/sh -c "while true; do sleep 30; done"
    volumes:
      - ..:/app
      - bundle_cache:/bundle
    depends_on:
      - db
      - redis

  web:
    container_name: currency_rate-web
    image: registry.rezerbit.com/currency_rate/app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    working_dir: /app
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpack
    command: 'bash -c "rm -f /var/run/rails.pid && bundle exec rails s -b 0.0.0.0 -p 80 --pid /var/run/rails.pid"'
    volumes:
      - ..:/app
      - bundle_cache:/bundle
    ports:
      - 80:80
    depends_on:
      - db
      - redis
      - sidekiq
      - app

  webpack:
    container_name: currency_rate-webpack
    image: registry.rezerbit.com/currency_rate/app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    working_dir: /app
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: 'bash -c "bin/webpack-dev-server"'
    volumes:
      - ..:/app
      - bundle_cache:/bundle
    ports:
      - 3035:3035
    depends_on:
      - db
      - app

  db:
    container_name: currency_rate-db
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    container_name: currency_rate-redis
    image: redis:4-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  sidekiq:
    container_name: currency_rate-sidekiq
    image: registry.rezerbit.com/currency_rate/app
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - ..:/app
      - bundle_cache:/bundle
    depends_on:
      - db
      - redis
      - app

volumes:
  bundle_cache:
  pg-data:
  redis-data:
